[book]
authors = ["Dave Bryson"]
language = "en"
multilingual = false
src = "src"
title = "Simular Documentation"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/simular-fi/simular"
git-repository-icon = "fa-github"

[output.html.print]
enable = true     # include support for printable output
page-break = true
