name: build-linux

on:
  workflow_dispatch

jobs:
  check_pyo3:
    runs-on: ubuntu-22.04
    steps:
      - name: Release from main
        if: github.ref == 'refs/heads/uppy03'
        run: echo '::notice ::Building and uploading release'
      - name: No release
        if: github.ref != 'refs/heads/uppy03'
        run: echo '::warning ::test only be run from the uppy03 branch!' && exit 1

  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          - runner: ubuntu-22.04
            target: aarch64
          - runner: ubuntu-22.04
            target: armv7
    needs: [check_pyo3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: auto
